InternetPhotoAlbum.MVC/Controllers/AlbumsController.cs
using AutoMapper;
using InternetPhotoAlbum.BLL.Infrastructure;
using InternetPhotoAlbum.BLL.Interfaces;
using InternetPhotoAlbum.BLL.Models;
using InternetPhotoAlbum.MVC.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace InternetPhotoAlbum.MVC.Controllers
{
    /// <summary>
    /// Controlling requests for albums
    /// </summary>
    public class AlbumsController : Controller
    {
        private readonly IAlbumService _albumService;
        private readonly IMapper _mapper;

        /// <summary>
        /// Inject album service and mapper
        /// </summary>
        /// <param name="albumService">Album service</param>
        /// <param name="mapper">Mapper</param>
        public AlbumsController(IAlbumService albumService, IMapper mapper)
        {
            _albumService = albumService;
            _mapper = mapper;
        }

        /// <summary>
        /// Process the GET request for index albums
        /// </summary>
        /// <returns>Result of action</returns>
        [HttpGet]
        public ActionResult Index()
        {
            var albums = _albumService.FindAll();

            ViewData["IsHavePermission"] = false;

            return View(albums);
        }

        /// <summary>
        /// Process the GET request for user's albums
        /// </summary>
        /// <param name="userId">User's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Route("{userId}")]
        public ActionResult UserAlbums(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                userId = User.Identity.GetUserId();
            }

            var albums = _albumService.FindByUserId(userId);

            bool isHavePermission = false;

            if (User.Identity is ClaimsIdentity claimsIdentity)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    var userIdValue = userIdClaim.Value;
                    isHavePermission = userIdValue == userId;
                }
            }

            ViewData["IsHavePermission"] = isHavePermission;

            return View("Index", albums);
        }

        /// <summary>
        /// Process the GET request for create album
        /// </summary>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            return PartialView();
        }

        /// <summary>
        /// Process the POST request for create album
        /// </summary>
        /// <param name="model">Album's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AlbumViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var dtoModel = _mapper.Map<AlbumDTO>(model);
                    dtoModel.UserId = User.Identity.GetUserId();
                    var result = await _albumService.CreateAsync(dtoModel);
                    return Json(new { url = Url.Action("UserAlbums") });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        /// <summary>
        /// Process the GET request for edit album
        /// </summary>
        /// <param name="id">Album's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id != null)
            {
                try
                {
                    var album = await _albumService.FindByIdAsync(id.Value);
                    if (CheckPermission(album.UserId))
                    {
                        return PartialView(album);
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                    }
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        /// <summary>
        /// Process the POST request for edit album
        /// </summary>
        /// <param name="model">Album's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AlbumDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _albumService.UpdateAsync(model);
                    return Json(new { url = Url.Action("UserAlbums") });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        /// <summary>
        /// Process the GET request for delete album
        /// </summary>
        /// <param name="id">Album's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id != null)
            {
                try
                {
                    var album = await _albumService.FindByIdAsync(id.Value);
                    if (CheckPermission(album.UserId))
                    {
                        return PartialView(album);
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                    }
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        /// <summary>
        /// Process the POST request for delete album
        /// </summary>
        /// <param name="id">Album's identifier</param>
        /// <returns>Result of action</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _albumService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _albumService.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool CheckPermission(string userId)
        {
            var authenticatedUserId = User.Identity.GetUserId();
            return authenticatedUserId == userId;
        }
    }
}

InternetPhotoAlbum.MVC/Controllers/GendersController.cs
using InternetPhotoAlbum.BLL.Infrastructure;
using InternetPhotoAlbum.BLL.Interfaces;
using InternetPhotoAlbum.BLL.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace InternetPhotoAlbum.MVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class GendersController : Controller
    {
        private readonly IGenderService _genderService;

        /// <summary>
        /// Inject gender service
        /// </summary>
        /// <param name="genderService">Gender service</param>
        public GendersController(IGenderService genderService)
        {
            _genderService = genderService;
        }

        /// <summary>
        /// Process the GET request for index genders
        /// </summary>
        /// <returns>Result of action</returns>
        [HttpGet]
        public ActionResult Index()
        {
            var genders = _genderService.FindAll();

            return View(genders);
        }

        /// <summary>
        /// Process the GET request for create gender
        /// </summary>
        /// <returns>Result of action</returns>
        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }

        /// <summary>
        /// Process the POST request for create gender
        /// </summary>
        /// <param name="model">Gender's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(GenderDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _genderService.CreateAsync(model);
                    return Json(new { url = Url.Action("Index") });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        /// <summary>
        /// Process the GET request for edit gender
        /// </summary>
        /// <param name="id">Gender's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id != null)
            {
                try
                {
                    var album = await _genderService.FindByIdAsync(id.Value);
                    return PartialView(album);
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        /// <summary>
        /// Process the POST request for edit gender
        /// </summary>
        /// <param name="model">Gender's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(GenderDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _genderService.UpdateAsync(model);
                    return Json(new { url = Url.Action("Index") });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        /// <summary>
        /// Process the GET request for delete gender
        /// </summary>
        /// <param name="id">Gender's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id != null)
            {
                try
                {
                    var album = await _genderService.FindByIdAsync(id.Value);
                    return PartialView(album);
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        /// <summary>
        /// Process the POST request for delete gender
        /// </summary>
        /// <param name="id">Gender's identifier</param>
        /// <returns>Result of action</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _genderService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _genderService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InternetPhotoAlbum.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Internet Photo Album</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm">
        <div class="container">
            @Html.ActionLink("Internet Photo Album", "Index", "Albums", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Albums", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Log in", "Login", "Account", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        
                        if (User.IsInRole("admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Administration</a>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("User Management", "Index", "Account", new { area = "" }, new { @class = "dropdown-item" })
                                    </li>
                                    <li>
                                        @Html.ActionLink("Gender Management", "Index", "Genders", new { area = "" }, new { @class = "dropdown-item" })
                                    </li>
                                    <li>
                                        @Html.ActionLink("Type of like Management", "Index", "LikeTypes", new { area = "" }, new { @class = "dropdown-item" })
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Welcome, @User.Identity.Name</a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("My Profile", "Details", "Account", new { area = "", id = User.Identity.GetUserId() }
                                        , new { @class = "dropdown-item" })
                                </li>
                                <li>
                                    @Html.ActionLink("My Albums", "UserAlbums", "Albums", new { area = "" }
                                        , new { @class = "dropdown-item" })
                                </li>
                                <li>
                                    @Html.ActionLink("Log out", "Logout", "Account", new { area = "" }, new { @class = "dropdown-item" })
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mykhailo Teziaiev</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>