InternetPhotoAlbum.MVC/Controllers/RatingsController.cs
using InternetPhotoAlbum.BLL.Interfaces;
using InternetPhotoAlbum.BLL.Models;
using Microsoft.AspNet.Identity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace InternetPhotoAlbum.MVC.Controllers
{
    /// <summary>
    /// Controlling requests for ratings
    /// </summary>
    public class RatingsController : Controller
    {
        private readonly IRatingService _ratingService;

        /// <summary>
        /// Inject rating service
        /// </summary>
        /// <param name="ratingService">Rating service</param>
        public RatingsController(IRatingService ratingService)
        {
            _ratingService = ratingService;
        }

        /// <summary>
        /// Process the POST request for rate image
        /// </summary>
        /// <param name="imageId">Image's identifier</param>
        /// <param name="likeId">Type of like's identifier</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> RateImage(int? imageId, int? likeId)
        {
            if (!(imageId == null || likeId == null))
            {
                var userId = User.Identity.GetUserId();
                var model = new RatingDTO
                {
                    ImageId = imageId.Value,
                    UserId = userId,
                    LikeTypeId = likeId.Value,
                };
                await _ratingService.RateImage(model);
                return RedirectToAction("Details", "Images", new { id = imageId });
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _ratingService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InternetPhotoAlbum.MVC/Views/Ratings/ImageRating.cshtml
@model (int imageId, int likeId)

@using (Html.BeginForm("RateImage", "Ratings", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container w-50 mx-auto">
        <input type="hidden" id="imageId" name="imageId" value="@Model.imageId" />
        <div class="btn-group w-100">
            <input type="radio" class="btn-check" name="likeId" id="likeId1" autocomplete="off" value="1" />
            <label class="btn btn-outline-primary" for="likeId1"><span class="bi bi-hand-thumbs-up"></span> Like</label>

            <input type="radio" class="btn-check" name="likeId" id="likeId2" autocomplete="off" value="2" />
            <label class="btn btn-outline-primary" for="likeId2"><span class="bi bi-hand-thumbs-down"></span> Unlike</label>
        </div>
    </div>
}

@section Scripts
{
    <script type="text/javascript">

        $(function()
        {
            if(@Model.likeId > 0)
            {
                const likeId = "likeId" + str(@Model.likeId);
                $(likeId).prop('checked', true);
            }

            $("input[name=likeId]").change(function()
            {
                $(this).parents("form").submit();
            });
        });

    </script>
}