InternetPhotoAlbum.MVC/Controllers/LikeTypesController.cs
using InternetPhotoAlbum.BLL.Infrastructure;
using InternetPhotoAlbum.BLL.Interfaces;
using InternetPhotoAlbum.BLL.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace InternetPhotoAlbum.MVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class LikeTypesController : Controller
    {
        private readonly ILikeTypeService _likeTypeService;

        /// <summary>
        /// Inject gender service
        /// </summary>
        /// <param name="genderService">Gender service</param>
        public LikeTypesController(ILikeTypeService likeTypeService)
        {
            _likeTypeService = likeTypeService;
        }

        /// <summary>
        /// Process the GET request for index genders
        /// </summary>
        /// <returns>Result of action</returns>
        [HttpGet]
        public ActionResult Index()
        {
            var likeTypes = _likeTypeService.FindAll();

            return View(likeTypes);
        }

        /// <summary>
        /// Process the GET request for create gender
        /// </summary>
        /// <returns>Result of action</returns>
        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }

        /// <summary>
        /// Process the POST request for create gender
        /// </summary>
        /// <param name="model">Gender's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LikeTypeDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _likeTypeService.CreateAsync(model);
                    return Json(new { url = Url.Action("Index") });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        /// <summary>
        /// Process the GET request for edit gender
        /// </summary>
        /// <param name="id">Gender's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id != null)
            {
                try
                {
                    var album = await _likeTypeService.FindByIdAsync(id.Value);
                    return PartialView(album);
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        /// <summary>
        /// Process the POST request for edit gender
        /// </summary>
        /// <param name="model">Gender's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LikeTypeDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _likeTypeService.UpdateAsync(model);
                    return Json(new { url = Url.Action("Index") });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        /// <summary>
        /// Process the GET request for delete gender
        /// </summary>
        /// <param name="id">Gender's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id != null)
            {
                try
                {
                    var album = await _likeTypeService.FindByIdAsync(id.Value);
                    return PartialView(album);
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        /// <summary>
        /// Process the POST request for delete gender
        /// </summary>
        /// <param name="id">Gender's identifier</param>
        /// <returns>Result of action</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _likeTypeService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _likeTypeService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InternetPhotoAlbum.MVC/Views/LikeTypes/Create.cshtml
@model InternetPhotoAlbum.BLL.Models.GenderDTO

@using (Ajax.BeginForm("Create", "LikeTypes", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "modalChangePart", OnSuccess = "OnSuccess" }))
{
    <div class="modal-content" id="modalChangePart">

        <div class="modal-header">
            <h4 class="modal-title">Add type of like</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>

        <div class="modal-body">
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-6 mx-auto">
                <div class="form-floating mb-3 mt-3">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter name" } })
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "ms-2" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="modal-footer col-3 mx-auto">
            <input type="submit" value="Add type of like" class="btn btn-info text-light" />
        </div>
    </div>
}

InternetPhotoAlbum.MVC/Views/LikeTypes/Delete.cshtml
@model InternetPhotoAlbum.BLL.Models.GenderDTO

<div class="modal-content">

    <div class="modal-header">
        <h4 class="modal-title">Delete gender @Model.Name</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
    </div>

    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    </div>

    <div class="modal-footer col-3 mx-auto">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <input type="submit" value="Delete" class="btn btn-info text-light" />
        }
    </div>

</div>

InternetPhotoAlbum.MVC/Views/LikeTypes/Edit.cshtml
@model InternetPhotoAlbum.BLL.Models.GenderDTO

@using (Ajax.BeginForm("Edit", "LikeTypes", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "modalChangePart", OnSuccess = "OnSuccess" }))
{
    <div class="modal-content" id="modalChangePart">

        <div class="modal-header">
            <h4 class="modal-title">Edit gender @Model.Name</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>

        <div class="modal-body">
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="col-6 mx-auto">
                <div class="form-floating mb-3 mt-3">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter name" } })
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "ms-2" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="modal-footer col-3 mx-auto">
            <input type="submit" value="Save" class="btn btn-info text-light" />
        </div>
    </div>
}

InternetPhotoAlbum.MVC/Views/LikeTypes/Index.cshtml
@model IEnumerable<InternetPhotoAlbum.BLL.Models.LikeTypeDTO>

@{
    ViewBag.Title = "Types of like";
}

<h2>Types of like</h2>

<p>
    @Html.ActionLink("Add type of like", "Create", new { area = "" }, new { id = "createDialLink", @class = "btn btn-success" })
</p>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "editDialLink btn btn-warning" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "deleteDialLink btn btn-danger" })
            </td>
        </tr>
    }

</table>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-ajax")

    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $("#createDialLink").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });

            $(".editDialLink").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });

            $(".deleteDialLink").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        });

        function OnSuccess(result) {
            if (result.url) {
                window.location.href = result.url;
            }
        }

    </script>
}