InternetPhotoAlbum.MVC/Controllers/ImagesController.cs
using AutoMapper;
using InternetPhotoAlbum.BLL.Infrastructure;
using InternetPhotoAlbum.BLL.Interfaces;
using InternetPhotoAlbum.BLL.Models;
using InternetPhotoAlbum.MVC.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace InternetPhotoAlbum.MVC.Controllers
{
    /// <summary>
    /// Controlling requests for images
    /// </summary>
    public class ImagesController : Controller
    {
        private readonly IAlbumService _albumService;
        private readonly IImageService _imageService;
        private readonly IRatingService _ratingService;
        private readonly IMapper _mapper;

        /// <summary>
        /// Inject album, image, rating services and mapper
        /// </summary>
        /// <param name="albumService">Album service</param>
        /// <param name="imageService">Image service</param>
        /// <param name="ratingService">Rating service</param>
        /// <param name="mapper">Mapper</param>
        public ImagesController(IAlbumService albumService, IImageService imageService, IRatingService ratingService, IMapper mapper)
        {
            _albumService = albumService;
            _imageService = imageService;
            _ratingService = ratingService;
            _mapper = mapper;
        }



        /// <summary>
        /// Process the GET request for index images
        /// </summary>
        /// <param name="albumId">Album's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        public async Task<ActionResult> Index(int? albumId)
        {
            if (albumId == null)
            {
                return HttpNotFound();
            }

            var images = _imageService.FindByAlbumId(albumId.Value).ToList();
            var model = _mapper.Map<IEnumerable<IndexImageViewModel>>(images);

            var userId = User.Identity.GetUserId();
            var album = await _albumService.FindByIdAsync(albumId.Value);
            bool isHavePermission = userId == album.UserId;

            ViewData["IsHavePermission"] = isHavePermission;

            TempData["AlbumUserId"] = album.UserId;

            ViewData["AlbumId"] = albumId;

            return View(model);
        }

        /// <summary>
        /// Process the GET request for details image
        /// </summary>
        /// <param name="id">Image's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        public async Task<ActionResult> Details(int? id)
        {
            if (id != null)
            {
                try
                {
                    var userId = User.Identity.GetUserId();

                    var image = await _imageService.FindByIdAsync(id.Value);
                    var model = _mapper.Map<IndexImageViewModel>(image);

                    model.FinalRating = _ratingService.CalculateFinalRating(model.Id);

                    int likeId = 0;
                    RatingDTO ratingDTO = null;

                    try
                    {
                        ratingDTO = await _ratingService.FindByIdAsync(id.Value, userId);
                        likeId = ratingDTO.LikeTypeId;
                    }
                    catch (InvalidOperationException ex) when (ex.Message == "Rating doesn't exist")
                    {
                    }

                    bool isHavePermission = userId == (string)TempData.Peek("AlbumUserId");

                    ViewData["IsHavePermission"] = isHavePermission;

                    ViewData["LikeId"] = likeId;

                    return View(model);
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        /// <summary>
        /// Process the POST request for search images by title
        /// </summary>
        /// <param name="title">Image's title</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchByTitle([Required] string title)
        {
            if (!string.IsNullOrEmpty(title))
            {
                var image = _imageService.FindByTitle(title);
                var model = _mapper.Map<IEnumerable<IndexImageViewModel>>(image);

                return View("IndexByTitle", model);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        /// <summary>
        /// Process the GET request for create image
        /// </summary>
        /// <param name="albumId">Album's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Create(int? albumId)
        {
            if (albumId != null)
            {
                var album = await _albumService.FindByIdAsync(albumId.Value);

                if (CheckPermission(album.UserId))
                {
                    ViewData["AlbumId"] = albumId.Value;
                    return PartialView();
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }
            }

            return HttpNotFound();
        }

        /// <summary>
        /// Process the POST request for create image
        /// </summary>
        /// <param name="model">Image's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateImageViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var dtoModel = _mapper.Map<ImageDTO>(model);
                    var result = await _imageService.CreateAsync(dtoModel);
                    return Json(new { url = Url.Action("Index", new { albumId = model.AlbumId }) });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            ViewData["AlbumId"] = model.AlbumId;
            return PartialView(model);
        }

        /// <summary>
        /// Process the GET request for edit image
        /// </summary>
        /// <param name="id">Image's identifier</param>
        /// <returns>Result of action</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id != null)
            {
                try
                {
                    var image = await _imageService.FindByIdAsync(id.Value);

                    if (CheckPermission(image.UserId))
                    {
                        var model = _mapper.Map<EditImageViewModel>(image);
                        return PartialView(model);
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                    }
                }
                catch (InvalidOperationException ex)
                {
                    return HttpNotFound(ex.Message);
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        /// <summary>
        /// Process the POST request for edit image
        /// </summary>
        /// <param name="model">Image's model</param>
        /// <returns>Result of action</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditImageViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var dtoModel = _mapper.Map<ImageDTO>(model);
                    var result = await _imageService.UpdateAsync(dtoModel);
                    return Json(new { url = Url.Action("Index", new { albumId = model.AlbumId }) });
                }
                catch (AggregateValidationException ex)
                {
                    List<ValidationResult> validationResults = ex.ValidationResults;
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                catch (ArgumentNullException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        /// <summary>

InternetPhotoAlbum.MVC/Views/Images/Create.cshtml
@model InternetPhotoAlbum.MVC.Models.CreateImageViewModel

@using (Ajax.BeginForm("Create", "Images", new AjaxOptions() { HttpMethod = "POST",
    UpdateTargetId = "modalChangePart", OnSuccess = "OnSuccess" }, new { enctype = "multipart/form-data" }))
{
    <div class="modal-content" id="modalChangePart">

        <div class="modal-header">
            <h4 class="modal-title">Add image</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>

        <div class="modal-body">
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-6 mx-auto">
                <div class="form-floating mb-3 mt-3">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter title" } })
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "ms-2" })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>

                <div class="form-floating mb-3 mt-3">
                    @Html.EditorFor(model => model.Description,
                        new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter description", @style = "height: 25vmin" } })
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "ms-2" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>

                <div class="form-floating mb-3 mt-3">
                    <input type="file" id="File" name="File" class="form-control" />
                    <label for="File" class="ms-2 py-2">@Html.DisplayNameFor(m => m.File)</label>
                    @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
                </div>
            </div>

            <input type="hidden" id="AlbumId" name="AlbumId" value="@((int)ViewData["AlbumId"])" />
        </div>

        <div class="modal-footer col-3 mx-auto">
            <input type="submit" value="Add image" class="btn btn-info text-light" />
        </div>
    </div>
}

InternetPhotoAlbum.MVC/Views/Images/Delete.cshtml
@model InternetPhotoAlbum.MVC.Models.IndexImageViewModel

<div class="modal-content">

    <div class="modal-header">
        <h4 class="modal-title">Delete image @Model.Title</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
    </div>

    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>


    </div>

    <div class="modal-footer col-3 mx-auto">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <input type="submit" value="Delete" class="btn btn-info text-light" />
        }
    </div>

</div>

InternetPhotoAlbum.MVC/Views/Images/Details.cshtml
@model InternetPhotoAlbum.MVC.Models.IndexImageViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details about @Model.Title</h2>

@if ((bool)ViewData["IsHavePermission"])
{
    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>
}


<div class="card col-4 my-2 mx-auto">
    <img class="card-img-top col-12" src="data:@Model.ContentType;base64,@Model.File" alt="@Model.Title">
    <div class="card-body">
        <h4 class="card-title text-center">
            @Model.Title
            <span class="badge rounded-pill bg-info"><span class="bi bi-heart-fill"></span> @Model.FinalRating</span>
        </h4>
        <p class="card-text">@Model.Description</p>
        <p class="card-text"><em>@Model.AddedDate.ToString("f")</em></p>

        @if ((bool)ViewData["IsHavePermission"])
         {
            <div class="btn-group">
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "editDialLink btn btn-warning" })
                @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "deleteDialLink btn btn-danger" })
            </div>
         }
        else if(User.Identity.IsAuthenticated)
        {
            @Html.Partial("~/Views/Ratings/ImageRating.cshtml", (Model.Id, (int)ViewData["LikeId"]))
        }

            </div>
        </div>
<p>
    @Html.ActionLink("Back to Album", "Index", new { albumId = Model.AlbumId }, new { @class = "btn btn-info text-light" })
</p>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-ajax")

    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".editDialLink").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });

            $(".deleteDialLink").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });

            if(@((int)ViewData["LikeId"]) > 0)
            {
                const likeId = "#likeId" + @ViewData["LikeId"];
                $(likeId).prop('checked', true);
            }

            $("input[name=likeId]").click(function()
            {
                $(this).parents("form").submit();
            });
        });

        function OnSuccess(result) {
            if (result.url) {
                window.location.href = result.url;
            }
        }

    </script>
}

InternetPhotoAlbum.MVC/Views/Images/Edit.cshtml
@model InternetPhotoAlbum.MVC.Models.EditImageViewModel

@using (Ajax.BeginForm("Edit", "Images", new AjaxOptions() { HttpMethod = "POST",
    UpdateTargetId = "modalChangePart", OnSuccess = "OnSuccess" }, new { enctype = "multipart/form-data" }))
{
    <div class="modal-content" id="modalChangePart">

        <div class="modal-header">
            <h4 class="modal-title">Edit image @Model.Title</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>

        <div class="modal-body">
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.Id)

            <div class="col-6 mx-auto">
                <div class="form-floating mb-3 mt-3">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter title" } })
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "ms-2" })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>

                <div class="form-floating mb-3 mt-3">
                    @Html.EditorFor(model => model.Description,
                        new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter description", @style = "height: 25vmin" } })
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "ms-2" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.AlbumId)
            @Html.HiddenFor(model => model.ContentType)
        </div>

        <div class="modal-footer col-3 mx-auto">
            <input type="submit" value="Edit image" class="btn btn-info text-light" />
        </div>

    </div>
}

InternetPhotoAlbum.MVC/Views/Images/Index.cshtml
@model IEnumerable<InternetPhotoAlbum.MVC.Models.IndexImageViewModel>

@{
    ViewBag.Title = "Images";
}

<h2>Images</h2>

@if ((bool)ViewData["IsHavePermission"])
{
    <p>
        @Html.ActionLink("Add image", "Create", new { area = "",
            albumId = (int)ViewData["AlbumId"] }, new { id = "createDialLink", @class = "btn btn-success" })
    </p>

    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>
}

<div class="container">
    <div class="row row-cols-4">
        @foreach (var item in Model)
        {
            <div class="card col my-2">
                <img class="card-img-top col-12" src="data:@item.ContentType;base64,@item.File" alt="@item.Title">
                <div class="card-body">
                    <h4 class="card-title text-center">@Html.ActionLink(item.Title, "Details", new { id = item.Id })</h4>
                    <p class="card-text">@item.Description</p>
                </div>
            </div>
        }
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-ajax")

    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $("#createDialLink").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        });

        function OnSuccess(result) {
            if (result.url) {
                window.location.href = result.url;
            }
        }

    </script>
}

InternetPhotoAlbum.MVC/Views/Images/IndexByTitle.cshtml
@model IEnumerable<InternetPhotoAlbum.MVC.Models.IndexImageViewModel>

@{
    ViewBag.Title = "Images";
}

<h2>Images</h2>

<div class="container">
    <div class="row row-cols-4">
        @foreach (var item in Model)
        {
            <div class="card col my-2">
                <img class="card-img-top col-12" src="data:@item.ContentType;base64,@item.File" alt="@item.Title">
                <div class="card-body">
                    <h4 class="card-title text-center">@Html.ActionLink(item.Title, "Details", new { id = item.Id })</h4>
                    <p class="card-text">@item.Description</p>
                </div>
            </div>
        }
    </div>
</div>